In [1]:
import pandas as pd

In [2]:
#read gene expression file
gene_expression_file = "GSE44861_gene_expression.csv"
gene_expression = pd.read_csv(gene_expression_file)
gene_expression.head()

,ID_REF,GSM1092909,GSM1092910,GSM1092911,GSM1092912,GSM1092913,GSM1092914,GSM1092915,GSM1092916,GSM1092917,...,GSM1093010,GSM1093011,GSM1093012,GSM1093013,GSM1093014,GSM1093015,GSM1093016,GSM1093017,GSM1093018,GSM1093019
0,1007_s_at,11.76220,10.57850,10.88280,11.23300,10.05570,8.71981,10.10320,10.33610,10.40220,...,10.86280,11.00710,10.29540,11.60290,11.25600,8.48345,11.88840,10.01290,10.95720,11.48780
1,1053_at,6.29542,6.77451,6.30281,8.18885,6.27496,7.23963,6.32391,6.68181,5.83710,...,6.43236,7.97710,7.29078,6.65951,7.40641,7.51192,6.73369,6.51293,5.97877,7.62790
2,117_at,5.55660,5.58586,5.61578,6.09570,5.99864,6.77403,5.62292,5.62754,5.61482,...,5.99220,6.09308,5.68518,5.86398,6.06084,5.76128,5.53477,6.32736,5.79387,6.07889
3,121_at,7.81090,7.66729,8.43118,7.81232,7.52846,7.62669,8.14157,8.25435,8.44242,...,7.65229,7.55289,7.92830,7.95150,8.29067,7.30795,7.93035,7.96173,8.03345,7.52337
4,1255_g_at,5.24249,5.21854,5.33201,5.30253,5.30274,5.19317,5.39920,5.37089,5.60335,...,5.31678,5.23348,5.31793,5.15591,5.31438,5.52718,5.24126,5.07803,5.41318,5.22522

In [3]:
#index names are now replaced with gene id
gene_expression_file = "GSE44861_gene_expression.csv"
gene_expression = pd.read_csv(gene_expression_file, index_col=0) #index names are now replaced with gene id

In [4]:
gene_expression.head()

,GSM1092909,GSM1092910,GSM1092911,GSM1092912,GSM1092913,GSM1092914,GSM1092915,GSM1092916,GSM1092917,GSM1092918,...,GSM1093010,GSM1093011,GSM1093012,GSM1093013,GSM1093014,GSM1093015,GSM1093016,GSM1093017,GSM1093018,GSM1093019
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,11.76220,10.57850,10.88280,11.23300,10.05570,8.71981,10.10320,10.33610,10.40220,11.02090,...,10.86280,11.00710,10.29540,11.60290,11.25600,8.48345,11.88840,10.01290,10.95720,11.48780
1053_at,6.29542,6.77451,6.30281,8.18885,6.27496,7.23963,6.32391,6.68181,5.83710,7.12169,...,6.43236,7.97710,7.29078,6.65951,7.40641,7.51192,6.73369,6.51293,5.97877,7.62790
117_at,5.55660,5.58586,5.61578,6.09570,5.99864,6.77403,5.62292,5.62754,5.61482,5.58057,...,5.99220,6.09308,5.68518,5.86398,6.06084,5.76128,5.53477,6.32736,5.79387,6.07889
121_at,7.81090,7.66729,8.43118,7.81232,7.52846,7.62669,8.14157,8.25435,8.44242,7.45736,...,7.65229,7.55289,7.92830,7.95150,8.29067,7.30795,7.93035,7.96173,8.03345,7.52337
1255_g_at,5.24249,5.21854,5.33201,5.30253,5.30274,5.19317,5.39920,5.37089,5.60335,5.08455,...,5.31678,5.23348,5.31793,5.15591,5.31438,5.52718,5.24126,5.07803,5.41318,5.22522

In [5]:
gene_expression.describe()

,GSM1092909,GSM1092910,GSM1092911,GSM1092912,GSM1092913,GSM1092914,GSM1092915,GSM1092916,GSM1092917,GSM1092918,...,GSM1093010,GSM1093011,GSM1093012,GSM1093013,GSM1093014,GSM1093015,GSM1093016,GSM1093017,GSM1093018,GSM1093019
count,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,...,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000,22277.000000
mean,7.494774,7.490231,7.466246,7.530271,7.481402,7.463629,7.438939,7.446498,7.468122,7.501222,...,7.523588,7.527515,7.517235,7.515262,7.505761,7.473558,7.507887,7.523229,7.513758,7.526858
std,2.198380,2.154273,2.019763,2.187954,2.100017,2.114683,1.943224,1.962503,1.892209,2.182262,...,2.172232,2.206946,2.185644,2.193406,2.172811,2.050313,2.188118,2.209662,2.069348,2.227168
min,4.644890,4.668360,4.686550,4.702350,4.778990,4.661990,4.654360,4.703260,4.651400,4.584330,...,4.261710,4.240590,4.703090,4.605960,4.663790,4.482830,4.681880,4.664170,4.393220,4.654070
25%,5.627110,5.654380,5.827700,5.654180,5.688490,5.716640,5.877340,5.863320,5.969800,5.622460,...,5.662830,5.635250,5.660250,5.634120,5.647150,5.835000,5.647340,5.630350,5.782120,5.588660
50%,6.775240,6.802030,6.818480,6.867430,6.869100,6.763350,6.855280,6.875040,6.905880,6.866970,...,6.892670,6.873740,6.846880,6.858600,6.875910,6.811930,6.837630,6.875760,6.894770,6.888540
75%,9.012800,8.980800,8.730050,9.028720,8.915130,8.830520,8.618840,8.653220,8.622960,9.005610,...,9.046510,9.073140,9.004330,9.031650,8.988190,8.699350,8.997750,9.019830,8.890380,9.076690
max,15.373000,15.076800,15.444800,15.208300,15.209300,15.342100,15.410600,15.338400,15.275000,15.225800,...,15.327900,15.321000,15.295400,15.317600,15.335600,15.386100,15.357200,15.492600,15.384000,15.282600

In [6]:
gene_expression.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22277 entries, 1007_s_at to AFFX-TrpnX-M_at
Columns: 111 entries, GSM1092909 to GSM1093019
dtypes: float64(111)
memory usage: 19.0+ MB

In [7]:
gene_expression.shape

(22277, 111)

In [8]:
gene_expression.columns

Index(['GSM1092909', 'GSM1092910', 'GSM1092911', 'GSM1092912', 'GSM1092913',
       'GSM1092914', 'GSM1092915', 'GSM1092916', 'GSM1092917', 'GSM1092918',
       ...
       'GSM1093010', 'GSM1093011', 'GSM1093012', 'GSM1093013', 'GSM1093014',
       'GSM1093015', 'GSM1093016', 'GSM1093017', 'GSM1093018', 'GSM1093019'],
      dtype='object', length=111)

In [9]:
gene_expression.isnull().sum()

GSM1092909    0
GSM1092910    0
GSM1092911    0
GSM1092912    0
GSM1092913    0
             ..
GSM1093015    0
GSM1093016    0
GSM1093017    0
GSM1093018    0
GSM1093019    0
Length: 111, dtype: int64

In [10]:
# temporarily allow full output for columns to see all column result
#pd.set_option('display.max_rows', None)

#gene_expression.isnull().sum()

In [11]:
# Reset the option back to default
#pd.reset_option('display.max_rows')

In [12]:
# total columns with nulls
columns_with_null_count = (gene_expression.isnull().sum() > 0).sum()

# total columns without nulls
columns_without_null_count = (gene_expression.isnull().sum() == 0).sum()

print(f"Columns with Nulls: {columns_with_null_count}")
print(f"Columns without Nulls: {columns_without_null_count}")

Columns with Nulls: 0
Columns without Nulls: 111