In [1]:
import pandas as pd

In [2]:
# gene expression data
gene_expression_path = "GSE44076_gene_expression.csv"
gene_expression = pd.read_csv(gene_expression_path)

In [3]:
gene_expression.head()

,ID_REF,GSM1077598,GSM1077599,GSM1077600,GSM1077601,GSM1077602,GSM1077603,GSM1077604,GSM1077605,GSM1077606,...,GSM1077834,GSM1077835,GSM1077836,GSM1077837,GSM1077838,GSM1077839,GSM1077840,GSM1077841,GSM1077842,GSM1077843
0,11715100_at,3.6599,2.5712,3.3174,3.1835,2.9949,3.4481,3.1692,3.5142,2.7073,...,3.2312,4.4599,3.8468,3.8416,4.2620,2.7624,2.5775,3.1441,4.8256,3.3535
1,11715101_s_at,4.1524,4.1879,4.1040,4.3635,4.5227,4.1203,4.2486,4.1462,3.8748,...,3.8795,5.7232,4.7099,4.0111,4.9795,3.7898,3.7737,4.3357,5.4895,4.4803
2,11715102_x_at,3.3896,3.1228,3.2434,3.1175,3.3627,2.8233,3.4594,3.1960,3.1082,...,3.3990,5.1110,4.2058,3.2759,4.4833,3.0972,2.7807,3.4050,4.4170,3.2669
3,11715103_x_at,3.8929,3.7299,4.1048,3.3426,3.3376,3.0590,3.2893,3.2290,2.9375,...,3.7911,3.1532,4.2702,3.4329,3.5422,4.3038,3.2338,3.4187,4.6358,4.1998
4,11715104_s_at,7.3799,7.7642,6.4705,7.0046,6.9029,6.1424,6.5051,6.4659,6.6958,...,2.6693,2.6769,2.7843,2.6698,2.8176,3.0904,2.6377,3.0226,2.7754,2.3838

In [4]:
# Transpose the gene expression data to make geo_accession a column
gene_expression_transposed = gene_expression.set_index("ID_REF").transpose()
gene_expression_transposed.index.name = "geo_accession"  # Rename the index
gene_expression_transposed.reset_index(inplace=True)  # Convert index to a column

In [5]:
gene_expression_transposed.head()

ID_REF,geo_accession,11715100_at,11715101_s_at,11715102_x_at,11715103_x_at,11715104_s_at,11715105_at,11715106_x_at,11715107_s_at,11715108_x_at,...,AFFX-r2-TagO-3_at,AFFX-r2-TagO-5_at,AFFX-r2-TagQ-3_at,AFFX-r2-TagQ-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,GSM1077598,3.6599,4.1524,3.3896,3.8929,7.3799,2.0732,2.8276,2.6345,2.5165,...,1.9475,2.1732,2.3173,2.0892,7.0313,4.8902,5.9995,2.1907,2.1474,2.1102
1,GSM1077599,2.5712,4.1879,3.1228,3.7299,7.7642,2.3151,2.8944,2.4020,2.5873,...,1.9056,1.9503,2.0665,2.0585,7.3201,5.2443,6.2646,1.9371,2.2677,2.3093
2,GSM1077600,3.3174,4.1040,3.2434,4.1048,6.4705,2.1824,2.7407,2.4271,2.5785,...,2.5070,2.4232,2.4662,2.2127,8.0270,5.8140,6.3628,2.1923,2.2233,2.2221
3,GSM1077601,3.1835,4.3635,3.1175,3.3426,7.0046,2.1961,2.4710,2.2932,2.3527,...,2.0228,2.7202,2.4453,2.3259,7.1081,4.7067,5.1356,2.0068,2.2773,2.2656
4,GSM1077602,2.9949,4.5227,3.3627,3.3376,6.9029,2.5087,2.8609,2.4833,2.3683,...,1.9309,2.1284,2.6587,2.4271,7.7353,5.2432,6.1207,2.1847,2.3030,2.1275

In [6]:
# gene expression data
metadata_filepath = "GSE44076_cleaned_metadata.csv"
metadata = pd.read_csv(metadata_filepath)

In [7]:
# Merge metadata with transposed gene expression data
merged_data = pd.merge(metadata, gene_expression_transposed, on="geo_accession")

# Save the merged data
merged_data.to_csv("GSE44076_merged_data.csv", index=False)
print("Merged data saved as GSE44076_merged_data.csv")

Merged data saved as GSE44076_merged_data.csv

In [8]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Columns: 49394 entries, geo_accession to AFFX-TrpnX-M_at
dtypes: float64(49386), int64(1), object(7)
memory usage: 92.7+ MB