In [1]:
import pandas as pd

In [2]:
#read all metadata
metadata_file = "GSE44076_metadata_all.csv" 
metadata = pd.read_csv(metadata_file)

In [3]:
metadata.describe()

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,sample_type,...,contact_email,contact_department,contact_institute,contact_address,contact_city,contact_state,contact_zip/postal_code,contact_country,supplementary_file,data_row_count
count,246,246,246,246,246,246,246,246,246,246,...,246,246,246,246,246,246,246,246,246,246
unique,246,246,1,1,1,1,1,3,1,3,...,1,1,1,1,1,1,1,1,246,1
top,"""Mucosa sample from A2119 healthy donnor""","""GSM1077598""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Normal distant colon mucosa cells""","""Homo sapiens""","""sample type: Normal""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
freq,1,1,246,246,246,246,246,98,246,98,...,246,246,246,246,246,246,246,246,1,246

In [4]:
metadata.head()

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,sample_type,...,contact_email,contact_department,contact_institute,contact_address,contact_city,contact_state,contact_zip/postal_code,contact_country,supplementary_file,data_row_count
0,"""Mucosa sample from A2119 healthy donnor""","""GSM1077598""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Healthy colon mucosa cells""","""Homo sapiens""","""sample type: Mucosa""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
1,"""Mucosa sample from A2142 healthy donnor""","""GSM1077599""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Healthy colon mucosa cells""","""Homo sapiens""","""sample type: Mucosa""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
2,"""Mucosa sample from B2104 healthy donnor""","""GSM1077600""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Healthy colon mucosa cells""","""Homo sapiens""","""sample type: Mucosa""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
3,"""Mucosa sample from B2127 healthy donnor""","""GSM1077601""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Healthy colon mucosa cells""","""Homo sapiens""","""sample type: Mucosa""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
4,"""Mucosa sample from B2150 healthy donnor""","""GSM1077602""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Healthy colon mucosa cells""","""Homo sapiens""","""sample type: Mucosa""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""

In [5]:
metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   title                    246 non-null    object
 1   geo_accession            246 non-null    object
 2   status                   246 non-null    object
 3   submission_date          246 non-null    object
 4   last_update_date         246 non-null    object
 5   type                     246 non-null    object
 6   channel_count            246 non-null    object
 7   source_name_ch1          246 non-null    object
 8   organism_ch1             246 non-null    object
 9   sample_type              246 non-null    object
 10  individual_id            246 non-null    object
 11  stage                    246 non-null    object
 12  location                 246 non-null    object
 13  gender                   246 non-null    object
 14  age                      246 non-null    object
 15  molecule_ch1             246 non-null    object
 16  extract_protocol_ch1     246 non-null    object
 17  label_ch1                246 non-null    object
 18  label_protocol_ch1       246 non-null    object
 19  taxid_ch1                246 non-null    object
 20  hyb_protocol             246 non-null    object
 21  scan_protocol            246 non-null    object
 22  data_processing          246 non-null    object
 23  platform_id              246 non-null    object
 24  contact_name             246 non-null    object
 25  contact_email            246 non-null    object
 26  contact_department       246 non-null    object
 27  contact_institute        246 non-null    object
 28  contact_address          246 non-null    object
 29  contact_city             246 non-null    object
 30  contact_state            246 non-null    object
 31  contact_zip/postal_code  246 non-null    object
 32  contact_country          246 non-null    object
 33  supplementary_file       246 non-null    object
 34  data_row_count           246 non-null    object
dtypes: object(35)
memory usage: 67.4+ KB

In [6]:
metadata.shape

(246, 35)

In [7]:
metadata.columns

Index(['title', 'geo_accession', 'status', 'submission_date',
       'last_update_date', 'type', 'channel_count', 'source_name_ch1',
       'organism_ch1', 'sample_type', 'individual_id', 'stage', 'location',
       'gender', 'age', 'molecule_ch1', 'extract_protocol_ch1', 'label_ch1',
       'label_protocol_ch1', 'taxid_ch1', 'hyb_protocol', 'scan_protocol',
       'data_processing', 'platform_id', 'contact_name', 'contact_email',
       'contact_department', 'contact_institute', 'contact_address',
       'contact_city', 'contact_state', 'contact_zip/postal_code',
       'contact_country', 'supplementary_file', 'data_row_count'],
      dtype='object')