In [1]:
import pandas as pd
import re

In [2]:
#file path
file_path = "GSE44076_series_matrix.txt"

# Read the file, ignoring comment lines and extracting metadata
metadata = {}
with open(file_path, "r") as file:
    for line in file:
        if line.startswith("!Sample_"):
            key, values = line.split("\t", 1)
            key = key.replace("!Sample_", "").strip()
            values = values.strip().split("\t")
            metadata[key] = values

df_metadata_all = pd.DataFrame(metadata)

# Identify and rename relevant metadata fields if needed
#relevant_columns = ["age", "sex", "disease state", "treatment", "other metadata fields"]
#for col in df_metadata_all.columns:
#    if any(keyword in col.lower() for keyword in relevant_columns):
 #       df_metadata.rename(columns={col: col.lower().replace(" ", "_")}, inplace=True)

# Display the first few rows of the metadata
print(df_metadata_all.head())

                                       title geo_accession  \
0  "Mucosa sample from A2119 healthy donnor"  "GSM1077598"
1  "Mucosa sample from A2142 healthy donnor"  "GSM1077599"
2  "Mucosa sample from B2104 healthy donnor"  "GSM1077600"
3  "Mucosa sample from B2127 healthy donnor"  "GSM1077601"
4  "Mucosa sample from B2150 healthy donnor"  "GSM1077602"

                    status submission_date last_update_date   type  \
0  "Public on Mar 14 2014"   "Feb 05 2013"    "Aug 31 2023"  "RNA"
1  "Public on Mar 14 2014"   "Feb 05 2013"    "Aug 31 2023"  "RNA"
2  "Public on Mar 14 2014"   "Feb 05 2013"    "Aug 31 2023"  "RNA"
3  "Public on Mar 14 2014"   "Feb 05 2013"    "Aug 31 2023"  "RNA"
4  "Public on Mar 14 2014"   "Feb 05 2013"    "Aug 31 2023"  "RNA"

  channel_count               source_name_ch1    organism_ch1  \
0           "1"  "Healthy colon mucosa cells"  "Homo sapiens"
1           "1"  "Healthy colon mucosa cells"  "Homo sapiens"
2           "1"  "Healthy colon mucosa cells"  "Homo sapiens"
3           "1"  "Healthy colon mucosa cells"  "Homo sapiens"
4           "1"  "Healthy colon mucosa cells"  "Homo sapiens"

  characteristics_ch1  ...               contact_email  \
0           "age: 62"  ...  "v.moreno@iconcologia.net"
1           "age: 77"  ...  "v.moreno@iconcologia.net"
2           "age: 78"  ...  "v.moreno@iconcologia.net"
3           "age: 65"  ...  "v.moreno@iconcologia.net"
4           "age: 52"  ...  "v.moreno@iconcologia.net"

                  contact_department                contact_institute  \
0  "Oncology Data Analytics Program"  "Catalan Institute of Oncology"
1  "Oncology Data Analytics Program"  "Catalan Institute of Oncology"
2  "Oncology Data Analytics Program"  "Catalan Institute of Oncology"
3  "Oncology Data Analytics Program"  "Catalan Institute of Oncology"
4  "Oncology Data Analytics Program"  "Catalan Institute of Oncology"

  contact_address                 contact_city contact_state  \
0   "Granvia 199"  "L'Hospitalet de Llobregat"   "Barcelona"
1   "Granvia 199"  "L'Hospitalet de Llobregat"   "Barcelona"
2   "Granvia 199"  "L'Hospitalet de Llobregat"   "Barcelona"
3   "Granvia 199"  "L'Hospitalet de Llobregat"   "Barcelona"
4   "Granvia 199"  "L'Hospitalet de Llobregat"   "Barcelona"

  contact_zip/postal_code contact_country  \
0                 "08908"         "Spain"
1                 "08908"         "Spain"
2                 "08908"         "Spain"
3                 "08908"         "Spain"
4                 "08908"         "Spain"

                                  supplementary_file data_row_count
0  "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...        "49386"
1  "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...        "49386"
2  "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...        "49386"
3  "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...        "49386"
4  "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...        "49386"

[5 rows x 30 columns]

In [3]:
# Save the metadata DataFrame to a CSV file
df_metadata_all.to_csv("GSE44076_metadata_all.csv", index=False)

In [4]:
print(list(df_metadata_all.columns))

['title', 'geo_accession', 'status', 'submission_date', 'last_update_date', 'type', 'channel_count', 'source_name_ch1', 'organism_ch1', 'characteristics_ch1', 'molecule_ch1', 'extract_protocol_ch1', 'label_ch1', 'label_protocol_ch1', 'taxid_ch1', 'hyb_protocol', 'scan_protocol', 'data_processing', 'platform_id', 'contact_name', 'contact_email', 'contact_department', 'contact_institute', 'contact_address', 'contact_city', 'contact_state', 'contact_zip/postal_code', 'contact_country', 'supplementary_file', 'data_row_count']

In [4]:
df_metadata_all.tail()

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name,organism_ch1,tissue_type,...,contact_email,contact_department,contact_institute,contact_address,contact_city,contact_state,contact_zip/postal_code,contact_country,supplementary_file,data_row_count
241,"""Tumor sample from Y2099 patient""","""GSM1077839""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Primary colon adenocarcinoma cells""","""Homo sapiens""","""sample type: Tumor""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
242,"""Tumor sample from Z2015 patient""","""GSM1077840""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Primary colon adenocarcinoma cells""","""Homo sapiens""","""sample type: Tumor""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
243,"""Tumor sample from Z2038 patient""","""GSM1077841""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Primary colon adenocarcinoma cells""","""Homo sapiens""","""sample type: Tumor""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
244,"""Tumor sample from Z2061 patient""","""GSM1077842""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Primary colon adenocarcinoma cells""","""Homo sapiens""","""sample type: Tumor""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""
245,"""Tumor sample from Z2084 patient""","""GSM1077843""","""Public on Mar 14 2014""","""Feb 05 2013""","""Aug 31 2023""","""RNA""","""1""","""Primary colon adenocarcinoma cells""","""Homo sapiens""","""sample type: Tumor""",...,"""v.moreno@iconcologia.net""","""Oncology Data Analytics Program""","""Catalan Institute of Oncology""","""Granvia 199""","""L'Hospitalet de Llobregat""","""Barcelona""","""08908""","""Spain""","""ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...","""49386"""

In [5]:
for col in df_metadata_all.columns:
    print(f"Column: {col}")
    print(df_metadata_all[col].head())  # Show first few values of each column
    print("-" * 50)

Column: title
0    "Mucosa sample from A2119 healthy donnor"
1    "Mucosa sample from A2142 healthy donnor"
2    "Mucosa sample from B2104 healthy donnor"
3    "Mucosa sample from B2127 healthy donnor"
4    "Mucosa sample from B2150 healthy donnor"
Name: title, dtype: object
--------------------------------------------------
Column: geo_accession
0    "GSM1077598"
1    "GSM1077599"
2    "GSM1077600"
3    "GSM1077601"
4    "GSM1077602"
Name: geo_accession, dtype: object
--------------------------------------------------
Column: status
0    "Public on Mar 14 2014"
1    "Public on Mar 14 2014"
2    "Public on Mar 14 2014"
3    "Public on Mar 14 2014"
4    "Public on Mar 14 2014"
Name: status, dtype: object
--------------------------------------------------
Column: submission_date
0    "Feb 05 2013"
1    "Feb 05 2013"
2    "Feb 05 2013"
3    "Feb 05 2013"
4    "Feb 05 2013"
Name: submission_date, dtype: object
--------------------------------------------------
Column: last_update_date
0    "Aug 31 2023"
1    "Aug 31 2023"
2    "Aug 31 2023"
3    "Aug 31 2023"
4    "Aug 31 2023"
Name: last_update_date, dtype: object
--------------------------------------------------
Column: type
0    "RNA"
1    "RNA"
2    "RNA"
3    "RNA"
4    "RNA"
Name: type, dtype: object
--------------------------------------------------
Column: channel_count
0    "1"
1    "1"
2    "1"
3    "1"
4    "1"
Name: channel_count, dtype: object
--------------------------------------------------
Column: source_name_ch1
0    "Healthy colon mucosa cells"
1    "Healthy colon mucosa cells"
2    "Healthy colon mucosa cells"
3    "Healthy colon mucosa cells"
4    "Healthy colon mucosa cells"
Name: source_name_ch1, dtype: object
--------------------------------------------------
Column: organism_ch1
0    "Homo sapiens"
1    "Homo sapiens"
2    "Homo sapiens"
3    "Homo sapiens"
4    "Homo sapiens"
Name: organism_ch1, dtype: object
--------------------------------------------------
Column: characteristics_ch1
0    "age: 62"
1    "age: 77"
2    "age: 78"
3    "age: 65"
4    "age: 52"
Name: characteristics_ch1, dtype: object
--------------------------------------------------
Column: molecule_ch1
0    "total RNA"
1    "total RNA"
2    "total RNA"
3    "total RNA"
4    "total RNA"
Name: molecule_ch1, dtype: object
--------------------------------------------------
Column: extract_protocol_ch1
0    "RNA was extracted from tissue samples using a...
1    "RNA was extracted from tissue samples using a...
2    "RNA was extracted from tissue samples using a...
3    "RNA was extracted from tissue samples using a...
4    "RNA was extracted from tissue samples using a...
Name: extract_protocol_ch1, dtype: object
--------------------------------------------------
Column: label_ch1
0    "biotin"
1    "biotin"
2    "biotin"
3    "biotin"
4    "biotin"
Name: label_ch1, dtype: object
--------------------------------------------------
Column: label_protocol_ch1
0    "RNA was labeled with the 3'-IVT Labeling Kit ...
1    "RNA was labeled with the 3'-IVT Labeling Kit ...
2    "RNA was labeled with the 3'-IVT Labeling Kit ...
3    "RNA was labeled with the 3'-IVT Labeling Kit ...
4    "RNA was labeled with the 3'-IVT Labeling Kit ...
Name: label_protocol_ch1, dtype: object
--------------------------------------------------
Column: taxid_ch1
0    "9606"
1    "9606"
2    "9606"
3    "9606"
4    "9606"
Name: taxid_ch1, dtype: object
--------------------------------------------------
Column: hyb_protocol
0    "RNA hybridization was performed through the A...
1    "RNA hybridization was performed through the A...
2    "RNA hybridization was performed through the A...
3    "RNA hybridization was performed through the A...
4    "RNA hybridization was performed through the A...
Name: hyb_protocol, dtype: object
--------------------------------------------------
Column: scan_protocol
0    "Human Genome U219 array plates were scanned a...
1    "Human Genome U219 array plates were scanned a...
2    "Human Genome U219 array plates were scanned a...
3    "Human Genome U219 array plates were scanned a...
4    "Human Genome U219 array plates were scanned a...
Name: scan_protocol, dtype: object
--------------------------------------------------
Column: data_processing
0    "The Robust Multi-array Average (RMA) algorith...
1    "The Robust Multi-array Average (RMA) algorith...
2    "The Robust Multi-array Average (RMA) algorith...
3    "The Robust Multi-array Average (RMA) algorith...
4    "The Robust Multi-array Average (RMA) algorith...
Name: data_processing, dtype: object
--------------------------------------------------
Column: platform_id
0    "GPL13667"
1    "GPL13667"
2    "GPL13667"
3    "GPL13667"
4    "GPL13667"
Name: platform_id, dtype: object
--------------------------------------------------
Column: contact_name
0    "Victor,,Moreno"
1    "Victor,,Moreno"
2    "Victor,,Moreno"
3    "Victor,,Moreno"
4    "Victor,,Moreno"
Name: contact_name, dtype: object
--------------------------------------------------
Column: contact_email
0    "v.moreno@iconcologia.net"
1    "v.moreno@iconcologia.net"
2    "v.moreno@iconcologia.net"
3    "v.moreno@iconcologia.net"
4    "v.moreno@iconcologia.net"
Name: contact_email, dtype: object
--------------------------------------------------
Column: contact_department
0    "Oncology Data Analytics Program"
1    "Oncology Data Analytics Program"
2    "Oncology Data Analytics Program"
3    "Oncology Data Analytics Program"
4    "Oncology Data Analytics Program"
Name: contact_department, dtype: object
--------------------------------------------------
Column: contact_institute
0    "Catalan Institute of Oncology"
1    "Catalan Institute of Oncology"
2    "Catalan Institute of Oncology"
3    "Catalan Institute of Oncology"
4    "Catalan Institute of Oncology"
Name: contact_institute, dtype: object
--------------------------------------------------
Column: contact_address
0    "Granvia 199"
1    "Granvia 199"
2    "Granvia 199"
3    "Granvia 199"
4    "Granvia 199"
Name: contact_address, dtype: object
--------------------------------------------------
Column: contact_city
0    "L'Hospitalet de Llobregat"
1    "L'Hospitalet de Llobregat"
2    "L'Hospitalet de Llobregat"
3    "L'Hospitalet de Llobregat"
4    "L'Hospitalet de Llobregat"
Name: contact_city, dtype: object
--------------------------------------------------
Column: contact_state
0    "Barcelona"
1    "Barcelona"
2    "Barcelona"
3    "Barcelona"
4    "Barcelona"
Name: contact_state, dtype: object
--------------------------------------------------
Column: contact_zip/postal_code
0    "08908"
1    "08908"
2    "08908"
3    "08908"
4    "08908"
Name: contact_zip/postal_code, dtype: object
--------------------------------------------------
Column: contact_country
0    "Spain"
1    "Spain"
2    "Spain"
3    "Spain"
4    "Spain"
Name: contact_country, dtype: object
--------------------------------------------------
Column: supplementary_file
0    "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...
1    "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...
2    "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...
3    "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...
4    "ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM107...
Name: supplementary_file, dtype: object
--------------------------------------------------
Column: data_row_count
0    "49386"
1    "49386"
2    "49386"
3    "49386"
4    "49386"
Name: data_row_count, dtype: object
--------------------------------------------------

In [6]:
#file_path = "GSE44076_metadata_updated.csv"
#df_metadata = pd.read_csv(file_path)
#df_metadata.head()

,title,geo_accession,type,source_name_ch1,individual_id,stage,location,Gender,age,molecule_ch1,data_processing,platform_id
0,"""Mucosa sample from A2119 healthy donnor""","""GSM1077598""","""sample type: Mucosa""","""Healthy colon mucosa cells""","""individual id: A2119""","""Stage: --""","""location: Left""","""gender: Male""","""age: 62""","""total RNA""","""The Robust Multi-array Average (RMA) algorith...","""GPL13667"""
1,"""Mucosa sample from A2142 healthy donnor""","""GSM1077599""","""sample type: Mucosa""","""Healthy colon mucosa cells""","""individual id: A2142""","""Stage: --""","""location: Left""","""gender: Female""","""age: 77""","""total RNA""","""The Robust Multi-array Average (RMA) algorith...","""GPL13667"""
2,"""Mucosa sample from B2104 healthy donnor""","""GSM1077600""","""sample type: Mucosa""","""Healthy colon mucosa cells""","""individual id: B2104""","""Stage: --""","""location: Left""","""gender: Female""","""age: 78""","""total RNA""","""The Robust Multi-array Average (RMA) algorith...","""GPL13667"""
3,"""Mucosa sample from B2127 healthy donnor""","""GSM1077601""","""sample type: Mucosa""","""Healthy colon mucosa cells""","""individual id: B2127""","""Stage: --""","""location: Right""","""gender: Male""","""age: 65""","""total RNA""","""The Robust Multi-array Average (RMA) algorith...","""GPL13667"""
4,"""Mucosa sample from B2150 healthy donnor""","""GSM1077602""","""sample type: Mucosa""","""Healthy colon mucosa cells""","""individual id: B2150""","""Stage: --""","""location: Right""","""gender: Female""","""age: 52""","""total RNA""","""The Robust Multi-array Average (RMA) algorith...","""GPL13667"""

In [6]:
file_path = "GSE44076_series_matrix.txt"
data = pd.read_csv(file_path, sep="\t", comment="!", header=0)
print(data.head())

          ID_REF  GSM1077598  GSM1077599  GSM1077600  GSM1077601  GSM1077602  \
0    11715100_at      3.6599      2.5712      3.3174      3.1835      2.9949
1  11715101_s_at      4.1524      4.1879      4.1040      4.3635      4.5227
2  11715102_x_at      3.3896      3.1228      3.2434      3.1175      3.3627
3  11715103_x_at      3.8929      3.7299      4.1048      3.3426      3.3376
4  11715104_s_at      7.3799      7.7642      6.4705      7.0046      6.9029

   GSM1077603  GSM1077604  GSM1077605  GSM1077606  ...  GSM1077834  \
0      3.4481      3.1692      3.5142      2.7073  ...      3.2312
1      4.1203      4.2486      4.1462      3.8748  ...      3.8795
2      2.8233      3.4594      3.1960      3.1082  ...      3.3990
3      3.0590      3.2893      3.2290      2.9375  ...      3.7911
4      6.1424      6.5051      6.4659      6.6958  ...      2.6693

   GSM1077835  GSM1077836  GSM1077837  GSM1077838  GSM1077839  GSM1077840  \
0      4.4599      3.8468      3.8416      4.2620      2.7624      2.5775
1      5.7232      4.7099      4.0111      4.9795      3.7898      3.7737
2      5.1110      4.2058      3.2759      4.4833      3.0972      2.7807
3      3.1532      4.2702      3.4329      3.5422      4.3038      3.2338
4      2.6769      2.7843      2.6698      2.8176      3.0904      2.6377

   GSM1077841  GSM1077842  GSM1077843
0      3.1441      4.8256      3.3535
1      4.3357      5.4895      4.4803
2      3.4050      4.4170      3.2669
3      3.4187      4.6358      4.1998
4      3.0226      2.7754      2.3838

[5 rows x 247 columns]

In [7]:
data

,ID_REF,GSM1077598,GSM1077599,GSM1077600,GSM1077601,GSM1077602,GSM1077603,GSM1077604,GSM1077605,GSM1077606,...,GSM1077834,GSM1077835,GSM1077836,GSM1077837,GSM1077838,GSM1077839,GSM1077840,GSM1077841,GSM1077842,GSM1077843
0,11715100_at,3.6599,2.5712,3.3174,3.1835,2.9949,3.4481,3.1692,3.5142,2.7073,...,3.2312,4.4599,3.8468,3.8416,4.2620,2.7624,2.5775,3.1441,4.8256,3.3535
1,11715101_s_at,4.1524,4.1879,4.1040,4.3635,4.5227,4.1203,4.2486,4.1462,3.8748,...,3.8795,5.7232,4.7099,4.0111,4.9795,3.7898,3.7737,4.3357,5.4895,4.4803
2,11715102_x_at,3.3896,3.1228,3.2434,3.1175,3.3627,2.8233,3.4594,3.1960,3.1082,...,3.3990,5.1110,4.2058,3.2759,4.4833,3.0972,2.7807,3.4050,4.4170,3.2669
3,11715103_x_at,3.8929,3.7299,4.1048,3.3426,3.3376,3.0590,3.2893,3.2290,2.9375,...,3.7911,3.1532,4.2702,3.4329,3.5422,4.3038,3.2338,3.4187,4.6358,4.1998
4,11715104_s_at,7.3799,7.7642,6.4705,7.0046,6.9029,6.1424,6.5051,6.4659,6.6958,...,2.6693,2.6769,2.7843,2.6698,2.8176,3.0904,2.6377,3.0226,2.7754,2.3838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49381,AFFX-ThrX-5_at,4.8902,5.2443,5.8140,4.7067,5.2432,5.8621,5.7176,4.0688,5.3388,...,5.0100,4.6559,4.4642,3.9253,4.4605,4.9615,4.9894,4.3336,4.9551,4.3106
49382,AFFX-ThrX-M_at,5.9995,6.2646,6.3628,5.1356,6.1207,7.1956,6.5755,5.2463,6.3274,...,5.8020,6.3594,5.3759,5.6525,5.3199,5.9032,5.8160,5.1489,6.0431,5.6033
49383,AFFX-TrpnX-3_at,2.1907,1.9371,2.1923,2.0068,2.1847,2.2407,1.8940,2.0712,1.9048,...,1.9564,2.0278,2.2097,2.1716,1.9210,2.0684,1.9110,2.1146,2.0207,2.0328
49384,AFFX-TrpnX-5_at,2.1474,2.2677,2.2233,2.2773,2.3030,2.2770,2.0634,2.3013,2.2326,...,1.9982,2.0774,2.1296,2.0454,2.0803,1.9758,2.1660,2.0619,2.2717,2.2460
49385,AFFX-TrpnX-M_at,2.1102,2.3093,2.2221,2.2656,2.1275,2.4722,2.4505,2.1832,2.1634,...,2.1991,2.1269,2.2233,2.2543,2.2014,2.2050,2.0183,2.0312,2.2361,2.1781

In [8]:
data.to_csv("GSE44076_gene_expression.csv", index=False)